# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43d5a80a8dd0be2403a2ef704ac05d6919f8b1ce31d3ef1cbfa4d9cabe69550be58871710c41151b417b6b59e6a186a9907be7c99d6b73191714aa4cce8096d9

test:
  secret_key_base: 4b465f6edc8b85ccbffa75e24ab664bb3ddf26017f7d7b6e38ef93176ee2084064dbba7f7130a65587208033ee6049b5150862cbb437bcbd31cae521930d9a55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
